// Code generated by ent, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAge holds the string denoting the age field in the database.
	FieldAge = "age"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeAdministered holds the string denoting the administered edge name in mutations.
	EdgeAdministered = "administered"
	// Table holds the table name of the user in the database.
	Table = "users"
	// AdministeredTable is the table that holds the administered relation/edge.
	AdministeredTable = "categories"
	// AdministeredInverseTable is the table name for the Category entity.
	// It exists in this package in order to avoid circular dependency with the "category" package.
	AdministeredInverseTable = "categories"
	// AdministeredColumn is the table column denoting the administered relation/edge.
	AdministeredColumn = "admin_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldAge,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)
